import type { Octokit } from "@octokit/rest";
import type { DocPatch } from "@doqtor/core-engine";

export interface PrCreationResult {
  prNumber: number;
  prUrl: string;
}

export class GitHubService {
  constructor(private octokit: Octokit) {}

  async getPrDiff(owner: string, repo: string, prNumber: number): Promise<string> {
    const { data } = await this.withRetry(() =>
      this.octokit.pulls.get({
        owner,
        repo,
        pull_number: prNumber,
        mediaType: { format: "diff" },
      }),
    );

    return data as unknown as string;
  }

  async getFileContent(
    owner: string,
    repo: string,
    path: string,
    ref: string,
  ): Promise<string | null> {
    try {
      const { data } = await this.withRetry(() =>
        this.octokit.repos.getContent({
          owner,
          repo,
          path,
          ref,
        }),
      );

      if ("content" in data && typeof data.content === "string") {
        return Buffer.from(data.content, "base64").toString("utf-8");
      }

      return null;
    } catch {
      return null;
    }
  }

  async createDocsPr(
    owner: string,
    repo: string,
    baseBranch: string,
    prNumber: number,
    patches: DocPatch[],
    summary: string,
  ): Promise<PrCreationResult> {
    const branchName = `doqtor/docs-update-pr-${prNumber}`;

    const baseRef = await this.withRetry(() =>
      this.octokit.git.getRef({
        owner,
        repo,
        ref: `heads/${baseBranch}`,
      }),
    );

    const baseSha = baseRef.data.object.sha;

    await this.withRetry(() =>
      this.octokit.git.createRef({
        owner,
        repo,
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      }),
    );

    const patchesByFile = new Map<string, DocPatch[]>();
    for (const patch of patches) {
      const existing = patchesByFile.get(patch.filePath) ?? [];
      existing.push(patch);
      patchesByFile.set(patch.filePath, existing);
    }

    for (const [filePath, filePatches] of patchesByFile) {
      await this.commitFilePatches(owner, repo, branchName, filePath, filePatches);
    }

    const { data: pr } = await this.withRetry(() =>
      this.octokit.pulls.create({
        owner,
        repo,
        title: `docs: update after #${prNumber}`,
        head: branchName,
        base: baseBranch,
        body: formatPrBody(prNumber, patches, summary),
      }),
    );

    return { prNumber: pr.number, prUrl: pr.html_url };
  }

  private async commitFilePatches(
    owner: string,
    repo: string,
    branch: string,
    filePath: string,
    patches: DocPatch[],
  ): Promise<void> {
    let existingSha: string | undefined;

    try {
      const { data } = await this.octokit.repos.getContent({
        owner,
        repo,
        path: filePath,
        ref: branch,
      });

      if ("sha" in data) {
        existingSha = data.sha;
      }
    } catch {
      // File doesn't exist yet
    }

    let content = existingSha
      ? await this.getFileContent(owner, repo, filePath, branch)
      : null;

    for (const patch of patches) {
      content = content
        ? content.replace(patch.oldText, patch.newText)
        : patch.newText;
    }

    await this.withRetry(() =>
      this.octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: filePath,
        message: `docs: update ${filePath}`,
        content: Buffer.from(content!).toString("base64"),
        branch,
        sha: existingSha,
      }),
    );
  }

  private async withRetry<T>(
    fn: () => Promise<T>,
    maxRetries = 3,
    baseDelay = 1000,
  ): Promise<T> {
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        return await fn();
      } catch (error: unknown) {
        const isRateLimit =
          error instanceof Error &&
          "status" in error &&
          (error as { status: number }).status === 403;

        if (!isRateLimit || attempt === maxRetries) {
          throw error;
        }

        const delay = baseDelay * Math.pow(2, attempt);
        await new Promise((resolve) => setTimeout(resolve, delay));
      }
    }

    throw new Error("Max retries exceeded");
  }
}

function formatPrBody(prNumber: number, patches: DocPatch[], summary: string): string {
  const changes = patches
    .map((p) => `- Updated \`${p.filePath}\` (${p.driftItem.type}: ${p.driftItem.symbolName})`)
    .join("\n");

  return `## Documentation Update

This PR updates documentation to reflect code changes from #${prNumber}.

### Changes

${changes}

### Summary

${summary}

---

*Generated by [Doqtor](https://github.com/cachevector/doqtor)*`;
}
